VAGRANTFILE_API_VERSION = "2"
machine_names=["web","db"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    machine_names.each_with_index do |name, machine_id|
        config.vm.define "centos6-wordpress-#{name}" do |machine|
            machine.vm.box = "centos/6"
            machine.vm.hostname = "centos6-wordpress-#{name}"
 
            machine.vm.network :forwarded_port, host: 80, guest: 80,  auto_correct: true # website
            machine.vm.network :forwarded_port, host: 443, guest: 443, auto_correct: true # ssl
            machine.vm.network :forwarded_port, host: 3306, guest: 3306, auto_correct: true # mysql
            ipaddr = "10.0.0.#{21+machine_id}"
            machine.vm.network :private_network, ip: "10.0.0.#{21+machine_id}"
            machine.vm.synced_folder "./", "/var/www/html", type: "rsync", id: "vagrant", :nfs => false,
                :mount_options => ["dmode=777", "fmode=666"]
  
            machine.vm.provider :libvirt do |libvirt|
                libvirt.memory = 1024
                libvirt.cpus = 1
            end

            machine.vm.provision "ansible" do |ansible|
                ansible.limit = ipaddr
                ansible.playbook = "playbook.yml"
                ansible.inventory_path = "hosts"
                ansible.sudo = true
            end
            machine.vm.provision :shell, inline: "echo Good job, now enjoy your new vbox: http://#{ipaddr}"
        end
    end
end
