apiVersion: v1
kind: Template
labels:
  template: memcached
metadata:
  annotations:
    description: Memcached is an in-memory key-value store.
    iconClass: icon-memcached
    tags: cache,memcached
  creationTimestamp: null
  name: memcached
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    portalIP: ""
    ports:
    - name: memcached-tcp
      nodePort: 0
      port: 11211
      protocol: TCP
      targetPort: 11211
    - name: memcached-udp
      nodePort: 0
      port: 11211
      protocol: UDP
      targetPort: 11211
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}
    annotations:
      iconClass: icon-memcached
  labels:
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MEMCACHED_MAX_MEMORY
            value: ${MEMCACHED_MAX_MEMORY}
          - name: MEMCACHED_MAX_CONNECTIONS
            value: ${MEMCACHED_MAX_CONNECTIONS}
          - name: MEMCACHED_EXTRA_PARAMETERS
            value: ${MEMCACHED_EXTRA_PARAMETERS}
          image: memcached
          imagePullPolicy: IfNotPresent
          name: memcached
          ports:
          - containerPort: 11211
            protocol: TCP
          - containerPort: 11211
            protocol: UDP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - memcached
        from:
          kind: ImageStreamTag
          name: memcached:latest
          namespace: openshift
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- description: Memcached service name
  name: NAME
  required: true
  value: "memcached"
- description: Max memory to use for items in megabytes
  name: MEMCACHED_MAX_MEMORY
  required: true
  value: "409"
- description: Max simultaneous connections
  name: MEMCACHED_MAX_CONNECTIONS
  required: false
  value: "10000"
- description: Extra command line parameters to start memcached
  name: MEMCACHED_EXTRA_PARAMETERS
  required: false
  value: ""
