specfile_path: packaging/leapp.spec

upstream_project_url: https://github.com/oamg/leapp
merge_pr_in_ci: false

srpm_build_deps: []

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
    - fedora-all-aarch64
    - fedora-all-x86_64
  actions:
    post-upstream-clone:
    # builds from PRs should have lower NVR than those from main branch
    - sed -i "s/1%{?dist}/0%{?dist}/g" packaging/leapp.spec
    get-current-version:
    # get version from spec file instead from git tag
    - bash -c "grep -m1 '^Version:' packaging/leapp.spec | grep -om1 '[0-9].[0-9.]**'"
- job: copr_build
  trigger: commit
  metadata:
    branch: main
    owner: "@oamg"
    project: leapp
    targets:
    - epel-8-x86_64
    - epel-9-x86_64
    - fedora-all-aarch64
    - fedora-all-x86_64
  actions:
    post-upstream-clone:
    # builds from main branch should have the highest NVR
    - sed -i "s/1%{?dist}/100%{?dist}/g" packaging/leapp.spec
    get-current-version:
    # get version from spec file instead from git tag
    - bash -c "grep -m1 '^Version:' packaging/leapp.spec | grep -om1 '[0-9].[0-9.]**'"


# NOTE: to see what envars, targets, .. can be set in tests, see
# the configuration of tests here:
#  7toX path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/rhel7/config.yaml
# >7tox path https://gitlab.cee.redhat.com/oamg/leapp-tests/-/blob/main/config.yaml
# Available only to RH Employees.


# ###################################################################### #
# ############################## 8 TO 9 ################################ #
# ###################################################################### #

# ###################################################################### #
# ### Abstract job definitions to make individual tests/jobs smaller ### #
# ###################################################################### #

#NOTE(pstodulk) putting default values in abstract jobs as from 8.10, as this
# is the last RHEL 8 release and all new future tests will start from this
# one release.

# This job is never triggered - we define abstract anchor that are reused in jobs that 'inherit'
# and have actionable triggers
- &sanity-abstract-8to9
  job: tests
  trigger: ignore
  fmf_url: "https://gitlab.cee.redhat.com/oamg/leapp-tests"
  fmf_ref: "main"
  use_internal_tf: True
  labels:
    - sanity
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: sanity-abstract-8to9
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9'
    environments:
      - artifacts: &artifacts-for-rhel8
        - type: "repository"
          id: "https://download.copr.fedorainfracloud.org/results/@oamg/leapp/epel-8-x86_64/"
          packages:
            - leapp-repository
            - python3-leapp
            - leapp-upgrade-el8toel9-deps
          order: 40
      - &tmt-env-settings-810to94
        tmt:
          context: &tmt-context-810to94
            distro: "rhel-8.10"
            distro_target: "rhel-9.4"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
      - &tmt-env-settings-810to96
        tmt:
          context: &tmt-context-810to96
            distro: "rhel-8.10"
            distro_target: "rhel-9.6"
        settings:
          provisioning:
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test

- &sanity-abstract-8to9-aws
  <<: *sanity-abstract-8to9
  labels:
    - sanity
    - aws
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10-rhui]
  identifier: sanity-abstract-8to9-aws

- &beaker-minimal-8to9-abstract-ondemand
  <<: *sanity-abstract-8to9
  manual_trigger: True
  labels:
    - beaker-minimal
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10.0-Nightly]
  identifier: beaker-minimal-8to9-abstract-ondemand

- &kernel-rt-abstract-8to9-ondemand
  <<: *beaker-minimal-8to9-abstract-ondemand
  labels:
    - kernel-rt
  identifier: sanity-8to9-kernel-rt-abstract-ondemand

# ###################################################################### #
# ############################# 8.10 > 9.4 ############################# #
# ###################################################################### #

- &sanity-810to94
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.4
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to94
  env: &env-810to94
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.4"

- &beaker-minimal-810to94
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to94
  env:
    <<: *env-810to94

- &kernel-rt-810to94
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.4
    - 8.10to9.4
  identifier: sanity-8.10to9.4-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to94
  env:
    <<: *env-810to94

- &sanity-810to94-aws
  <<: *sanity-abstract-8to9-aws
  trigger: pull_request
  targets:
    epel-8-x86_64:
      distros: [RHEL-8.10-rhui]
  identifier: sanity-8.10to9.4-aws
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:rhui-tier[0] & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - tmt:
          context: *tmt-context-810to94
        settings:
          provisioning:
            post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"
            tags:
              BusinessUnit: sst_upgrades@leapp_upstream_test
  env:
    <<: *env-810to94
    RHUI_HYPERSCALER: aws


# ###################################################################### #
# ############################# 8.10 > 9.6 ############################# #
# ###################################################################### #

- &sanity-810to96
  <<: *sanity-abstract-8to9
  trigger: pull_request
  identifier: sanity-8.10to9.6
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:tier0 & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to96
  env: &env-810to96
    SOURCE_RELEASE: "8.10"
    TARGET_RELEASE: "9.6"

# On-demand minimal beaker tests
- &beaker-minimal-810to95
  <<: *beaker-minimal-8to9-abstract-ondemand
  trigger: pull_request
  labels:
    - beaker-minimal
    - beaker-minimal-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-beaker-minimal-ondemand
  tf_extra_params:
    test:
      tmt:
        plan_filter: 'tag:8to9 & tag:partitioning & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to96
  env:
    <<: *env-810to96

# On-demand kernel-rt tests
- &kernel-rt-810to96
  <<: *kernel-rt-abstract-8to9-ondemand
  trigger: pull_request
  labels:
    - kernel-rt
    - kernel-rt-8.10to9.6
    - 8.10to9.6
  identifier: sanity-8.10to9.6-kernel-rt-ondemand
  tf_extra_params:
    test:
      tmt:
         plan_filter: 'tag:8to9 & tag:kernel-rt & enabled:true'
    environments:
      - artifacts: *artifacts-for-rhel8
      - *tmt-env-settings-810to96
  env:
    <<: *env-810to96
