VAGRANTFILE_API_VERSION = "2"

ipaddr = ENV.fetch('SRC_IP_ADDR', '10.0.0.42')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "centos7-ovirt-guest"

    config.vm.network :forwarded_port, guest: 443, host: 443, auto_correct: true
    config.vm.network :forwarded_port, guest: 80, host: 80, auto_correct: true
    config.vm.network :private_network, ip: ipaddr

    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        if libvirt.respond_to? :channel
            libvirt.channel :type => 'unix', :target_name => 'com.redhat.rhevm.vdsm', :target_type => 'virtio'
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
    end

    config.vm.provision :shell, inline: "echo Good job! Now vagrant ssh"
end
