VAGRANTFILE_API_VERSION = "2"

ipaddr = ENV.fetch('SRC_IP_ADDR', '10.0.0.10')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/6"
    config.vm.hostname = "centos6-app-vm"

    config.vm.network :forwarded_port, host: 80, guest: 80, auto_correct: true # website
    config.vm.network :forwarded_port, guest: 443, host: 443, auto_correct: true # ssl
    config.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true # mysql
    config.vm.network :forwarded_port, guest: 9000, host: 9000, auto_correct: true # phpmyadmin
    config.vm.network :private_network, ip: ipaddr
    config.vm.synced_folder "./", "/var/www/html", type: "rsync", id: "vagrant", :nfs => false,
        :mount_options => ["dmode=777", "fmode=666"]

    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
    end

    config.vm.provision :shell, inline: "echo Good job, now enjoy your new vbox: http://#{ipaddr}"

end
