VAGRANTFILE_API_VERSION = "2"

ipaddr = ENV.fetch('SRC_IP_ADDR', '10.0.0.10')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "centos7-mezzanine"

    config.vm.network :forwarded_port, host: 8000, guest: 8000, auto_correct: true # website
    config.vm.network :private_network, ip: ipaddr
    config.vm.synced_folder "./", "/var/www/html", type: "rsync", id: "vagrant", :nfs => false,
        :mount_options => ["dmode=777", "fmode=666"]

    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        if libvirt.respond_to? :channel
            libvirt.channel :type => 'unix', :target_name => 'com.redhat.rhevm.vdsm', :target_type => 'virtio'
        end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.sudo = true
    end

    config.vm.provision :shell, inline: "echo Good job, now enjoy your new vbox: http://#{ipaddr}"

end
