VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/7"
    config.vm.define "leapp-tests"
    config.vm.hostname = "leapp-tests-centos7-target"

    config.vm.network :private_network, ip: "10.0.0.11"

    config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
        libvirt.cpus = 1
        libvirt.cpu_mode = 'host-passthrough'
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.sudo = true
    end

    config.vm.provision :shell, inline: "echo Good job! Now vagrant ssh"
end
