FROM registry.access.redhat.com/ubi9/ubi:latest

VOLUME /payload

RUN dnf update -y && \
    dnf install python3 python39 make python3-pip -y && \
    python3 -m pip install --upgrade pip==20.3.4

RUN pip install virtualenv

WORKDIR /payload
ENTRYPOINT virtualenv testenv -p "/usr/bin/$PYTHON_VENV" && \
    source testenv/bin/activate  && \
    pip install -U setuptools && \
    pip install -U funcsigs && \
    pip install -U -r requirements-tests.txt && \
    pip install -U . && \
    export LINTABLES=$(find . -name '*.py' | grep -E -e '^\./leapp\/' -e '^\./tests/scripts/' | sort -u ) && \
    echo '==================================================' && \
    echo '==================================================' && \
    echo '===============   Running pylint   ===============' && \
    echo '==================================================' && \
    echo '==================================================' && \
    echo $LINTABLES | xargs pylint && echo '===> pylint PASSED' && \
    echo '==================================================' && \
    echo '==================================================' && \
    echo '===============   Running flake8   ===============' && \
    echo '==================================================' && \
    echo '==================================================' && \
	flake8 $LINTABLES && echo '===> flake8 PASSED'
