FROM registry.access.redhat.com/ubi9/ubi:latest

VOLUME /payload

RUN dnf update -y && \
    dnf install python3 python39 make python3-pip -y && \
    python3 -m pip install --upgrade pip==20.3.4

RUN pip install virtualenv

WORKDIR /payload
ENTRYPOINT virtualenv testenv -p "/usr/bin/$PYTHON_VENV" && \
    source testenv/bin/activate  && \
    pip install -U setuptools && \
    pip install -U funcsigs && \
    pip install -U -r requirements-tests.txt && \
    pip install -U . && \
    echo '==================================================' && \
    echo '==================================================' && \
    echo '===============   Running  tests   ===============' && \
    echo '==================================================' && \
    echo '==================================================' && \
    py.test -vv --cov-report term-missing --cov=leapp tests/scripts/*.py
